import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const SKILL_DIR = join(ROOT, 'skill', 'ui-standards');
export const REF_DIR = join(SKILL_DIR, 'references');
export const INDEX_PATH = join(REF_DIR, 'INDEX.md');
export const PROFILE_INDEXES = {
  web: ['FE-SHELL', 'FE-FEED', 'FE-FORM', 'FE-COLL', 'FE-SEL', 'FE-MEDIA', 'FE-ACCT', 'FE-COST', 'BE-API', 'BE-AUTH', 'BE-DATA', 'BE-FILE', 'BE-JOB', 'BE-OPS', 'BE-COST'],
  desktop: ['FE-SHELL', 'FE-FEED', 'FE-FORM', 'FE-COLL', 'FE-SEL', 'FE-MEDIA', 'FE-DESK', 'FE-COST', 'BE-DATA', 'BE-LOCAL', 'BE-COST'],
};

export const FAMILIES = {
  'FE-SHELL': 'frontend/shell.md',
  'FE-FEED': 'frontend/feedback.md',
  'FE-FORM': 'frontend/forms.md',
  'FE-COLL': 'frontend/collections.md',
  'FE-SEL': 'frontend/selection.md',
  'FE-MEDIA': 'frontend/media.md',
  'FE-ACCT': 'frontend/account.md',
  'FE-DESK': 'frontend/desktop.md',
  'FE-COST': 'frontend/metered-actions.md',
  'BE-API': 'backend/api.md',
  'BE-AUTH': 'backend/auth.md',
  'BE-DATA': 'backend/data.md',
  'BE-FILE': 'backend/files.md',
  'BE-JOB': 'backend/jobs.md',
  'BE-OPS': 'backend/ops.md',
  'BE-LOCAL': 'backend/local-first.md',
  'BE-COST': 'backend/metered-actions.md',
};

export const CODE_RE = /\b(?:FE|BE)-[A-Z]+-\d{2}\b/g;
const HEADING_RE = /^## ((?:FE|BE)-[A-Z]+-\d{2}) · (.+)$/;

export const read = (p) => readFileSync(p, 'utf8').replace(/\r\n/g, '\n');

export function listMarkdown(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true }).flatMap((d) => {
    const p = join(dir, d.name);
    if (d.isDirectory()) return listMarkdown(p);
    return d.name.endsWith('.md') ? [p] : [];
  });
}

export function parseEntries() {
  const entries = [];
  for (const [family, rel] of Object.entries(FAMILIES)) {
    const file = join(REF_DIR, rel);
    if (!existsSync(file)) {
      entries.push({ family, file: rel, missingFile: true });
      continue;
    }
    const lines = read(file).split('\n');
    let current = null;
    lines.forEach((line, i) => {
      if (line.startsWith('## ')) {
        const m = line.match(HEADING_RE);
        current = { family, file: rel, line: i + 1, heading: line, code: m?.[1], title: m?.[2], body: [] };
        entries.push(current);
      } else if (current) {
        current.body.push(line);
      }
    });
  }
  return entries;
}

export function field(body, name) {
  const line = body.find((l) => l.startsWith(`**${name}:**`));
  return line ? line.slice(name.length + 5).trim() : null;
}

export function buildIndex(entries) {
  const out = [
    '# INDEX — trigger words to entry codes',
    '',
    '<!-- GENERATED by scripts/build-index.mjs. Do not edit by hand. -->',
    '',
    'Match what the user is trying to do against the trigger words, then load only the',
    'family files listed. CORE-CARD.md always applies; load full CORE.md by target profile.',
    '',
  ];
  for (const [family, rel] of Object.entries(FAMILIES)) {
    const fam = entries.filter((e) => e.family === family && e.code);
    if (!fam.length) continue;
    out.push(`## ${family} · \`${rel}\``, '', '| Code | Title | Triggers |', '|---|---|---|');
    for (const e of fam) out.push(`| ${e.code} | ${e.title} | ${field(e.body, 'Triggers') ?? ''} |`);
    out.push('');
  }
  return out.join('\n');
}

export function buildProfileIndex(entries, profile) {
  const allowed = new Set(PROFILE_INDEXES[profile] ?? []);
  return buildIndex(entries.filter((e) => allowed.has(e.family)))
    .replace('# INDEX — trigger words to entry codes', `# ${profile.toUpperCase()} INDEX — trigger words to entry codes`);
}

export const relPath = (p) => relative(ROOT, p).replace(/\\/g, '/');
